export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL";



export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL";



export const PRODUCT_DELETE_REQUEST="PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS="PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL="PRODUCT_DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST="PRODUCT_DCREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS="PRODUCT_DCREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL="PRODUCT_DCREATE_FAIL";
export const PRODUCT_CREATE_RESET="PRODUCT_DCREATE_RESET";


export const PRODUCT_UPDATE_REQUEST="PRODUCT__UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS="PRODUCT__UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL="PRODUCT__UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET="PRODUCT__UPDATE_RESET";


export const PRODUCT_CREATE_REVIEW_REQUEST="PRODUCT__CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS="PRODUCT__CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL="PRODUCT__CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET="PRODUCT__CREATE_REVIEW_RESET";



